spring.application.name=noltok
spring.datasource.driver-class-name=${DB_DRIVER}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# JPA
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

# MinIO
minio.root-user=${MINIO_ROOT_USER}
minio.root-password=${MINIO_ROOT_PASSWORD}
minio.endpoint=${MINIO_ENDPOINT}
minio.bucket=${MINIO_BUCKET}

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB